# This file is part of the Stack Exchange Api Client library.
#
# Copyright (c) 2015 Be単at Espi単a <benatespina@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

use-sort:
    group-type: each
    sort-type: alph
    sort-direction: asc

header: |
    /*
     * This file is part of the Stack Exchange Api Client library.
     *
     * Copyright (c) 2015 Be単at Espi単a <benatespina@gmail.com>
     *
     * For the full copyright and license information, please view the LICENSE
     * file that was distributed with this source code.
     */
