# This file is part of the Stack Exchange Api Client library.
#
# Copyright (c) 2014-2016 Beñat Espiña <benatespina@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

sudo: false

language: php

php:
    - 5.6
    - 7.0
    - hhvm

env:
    - COMPOSER_OPTIONS="--prefer-source"

before_install:
    - '[[ "$TRAVIS_PHP_VERSION" == "hhvm" ]] || phpenv config-rm xdebug.ini'

install:
    - composer update --no-interaction ${COMPOSER_OPTIONS}

before_script:
    - cp test/behat.yml.dist behat.yml && cp test/phpspec.yml.dist phpspec.yml

script:
    - vendor/bin/phpspec run

    - vendor/bin/behat --stop-on-failure --suite=answer

cache:
    directories:
        - $COMPOSER_CACHE_DIR

matrix:
    fast_finish: true
