# This file is part of the Stack Exchange Api Client library.
#
# (c) Beñat Espiña <benatespina@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

sudo: false

language: php

php:
    - 7.1

addons:
    apt:
        packages:
            - xmlstarlet

before_install:
    - COMPOSER_OPTIONS="--prefer-source"
    - STEAC_ACCESS_TOKEN="${ACCESS_TOKEN} | sed 's/\\//g'"
    - STEAC_KEY="${KEY} | sed 's/\\//g'"

install:
    - composer install --no-interaction ${COMPOSER_OPTIONS}

before_script:
    - echo STEAC_ACCESS_TOKEN
    - echo STEAC_KEY
    - cp phpunit.xml.dist phpunit.xml
    - xmlstarlet ed --inplace -u '/phpunit/php/const[@value="{{ ACCESS_TOKEN }}"]/@value' -v '$STEAC_ACCESS_TOKEN' phpunit.xml
    - xmlstarlet ed --inplace -u '/phpunit/php/const[@value="{{ KEY }}"]/@value' -v '$STEAC_KEY' phpunit.xml

script:
    - vendor/bin/phpspec run
    - vendor/bin/phpunit

cache:
    directories:
        - $COMPOSER_CACHE_DIR

matrix:
    fast_finish: true
